language: java

addons:
  sonarcloud:
    organization: "1stian"
    token:
      secure: "bPx2lp5D5pJ+IRWiQasbNe2EFL9z05MEOVFv2Zdy7YJT7A3IvUZGyHs+iZzZrQuthBFEOsGA24KkCuimMWy5trLUDbSQTkr66hBltdbRzMRtVMhSW7025r0zu4hMxwmB9iFHW7mCfiGuQlxjAWMWvG/e2u72lNGFc+MKFNyuEd23rcX4jV7O0SHNyDiRi4Ulai8GSOiEX+Ng2Mypv3tTY0vYbJx7vmqPfJnT9EUNZkwInuuGdADEmli3jNqk6Tr7JidWlP+gOnjrnxdMRJZQtROBBGAPVtvAoFvEporwC9lntxjm5dxyMjmOTU5ZHdj9h/m6YtIy7QNwDNvMs2gpRxwzaLzSrQgD78UCtF7OuUgXear5JmsKo2wiVm+E83WkVlwEKAz+z6m5bcGM5vEyctXbI8IbffJkQ6G78AUuy+Nio3CIy7qbe/LZsobdlOn6sSVE7Qabftwh0Pc5RZ/KNBV/YkxTcPQ8TfNFxSrSv+rdm68ExV15RXZSxVEaCsjDCOqgE+vFBFFIQiv7PyoxvH1o/oyyXwztZlLPD/qseE3sZyMPsHo9V5Uqw6F8QchIQ+OnBqgxpT95Okylh1b6PUc3ofLI05ywei4QJFD4MWk4Q87EWDodttMolOobKLu165uHQwjSog1aBwnQXQLSOJ7vmZOPzcekZrfQdtNULW0="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
