#---------------------------1stian-------------
#----------------------------------------------
#--------------------OhWild--------------------
#-------------OhWild---------------------------
#------OhWild----------------------------------
# Created by Stian "1stian" Tofte
# https://ohneemc.com
#

debug: false
settings:
  # How often you may use the command. In seconds. -1 to disable.
  cooldown: 10
  # Cooldown for each world.
  enabled: false
  # What item to use to fill rest of the inventory slots.
  fillitem: GRAY_STAINED_GLASS_PANE
  # Size of the inventory
  size: 27
  # GUI name
  guiname: "&aOhWild"
  # Blocks not to land on
  unsafeblocks:
    - lava
    - water
    - air # Do not remove this one....
worlds:
  # World names need to be exact as the world name(Same as the folder).
  world:
    # What item to show for this world.
    item: oxeye_daisy
    # Cooldown(Only works if cooldown for each world is set under settings section)
    cooldown: 10
    # Which position you want it in.
    position: 12
    # Name for the item
    name: Overworld
    # Item lore
    lore:
      - "Random location"
      - "In the normal world"
      - "Have fun"
    # Radius around spawn that the player may be teleported to.
    radius: 5000
  world_nether:
    # What item to show for this world.
    item: nether_star
    # Cooldown(Only works if cooldown for each world is set under settings section)
    cooldown: 10
    # Which position you want it in.
    position: 14
    # Name for the item
    name: The nether
    # Item lore
    lore:
      - "Random location"
      - "In the nether world"
      - "Have fun"
    # Radius around spawn that the player may be teleported to.
    radius: 2500
messages:
  # Customizable messages. Leave empty to disable.
  #
  # Cooldown message, will be shown when a player uses the command before the cooldown is gone.
  cooldown: "&a{time} &7seconds before you can use wild again."
  # Message that will be shown for the player after a teleport.
  teleport: "&aSwosh"
ConfigVersion: 1.1